version: '3'

services:

  web: 
    image: zabbix/zabbix-web-apache-mysql:alpine-5.0-latest
    environment:
      TZ: America/Sao_Paulo
      PHP_TZ: America/Sao_Paulo
      ZBX_SERVER_NAME: ${WEBSERVER_FQDN}
      ZBX_SERVER_HOST: backend
      ZBX_TIMEOUT: 20
      ZBX_STARTPINGERS: 2
      DB_SERVER_HOST: database
      MYSQL_ROOT_PASSWORD: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix
    volumes:
      - zabbix-var:/var/lib/zabbix
      - zabbix-alertscripts:/usr/lib/zabbix/alertscripts
    #ports:
    #  - 10051:10051
    deploy:
      mode: replicated
      replicas: 1
      labels:
       - traefik.enable=true
       - traefik.port=8080
       - traefik.frontend.rule=Host:${WEBSERVER_FQDN}
       - traefik.protocol=http
       - traefik.docker.network=web
      placement:
        constraints:
         - node.labels.webserver == true
    networks:
      - web
      - default
      
  backend:
    #image: zabbix/zabbix-appliance:alpine-latest
    image: zabbix/zabbix-server-mysql:alpine-5.0-latest
    environment:
      TZ: America/Sao_Paulo
      PHP_TZ: America/Sao_Paulo
      ZBX_SERVER_NAME: ${WEBSERVER_FQDN}
      ZBX_TIMEOUT: 20
      ZBX_STARTPINGERS: 2
      DB_SERVER_HOST: database
      MYSQL_ROOT_PASSWORD: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix
    volumes:
      - zabbix-var:/var/lib/zabbix
      - zabbix-alertscripts:/usr/lib/zabbix/alertscripts
    #ports:
    #  - 10051:10051
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
         - node.labels.webserver == true
      
  database:
    image: mysql:5.7
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
         - node.labels.database == true
         
  agent:
    image: zabbix/zabbix-agent:alpine-5.0-latest
    environment:
      ZBX_HOSTNAME: "Zabbix server"
      ZBX_SERVER_HOST: zabbix5_backend,zabbix5_web
      # todo: detect service network here
      ZBX_SOURCEIP: 10.0.0.0/16
      #ZBX_ACTIVE_ALLOW: "true"
      #ZBX_ACTIVESERVERS: backend
      #ZBX_PASSIVE_ALLOW: "true"
      #ZBX_PASSIVESERVERS: backend
      ZBX_DEBUGLEVEL: 3
    deploy:
      #mode: global
      mode: replicated
      replicas: 1
      placement:
        constraints:
         - node.labels.webserver == true
      
volumes:
  zabbix-var:
    driver: local
  zabbix-alertscripts:
    driver: local
  mysql:
    driver: local
  
networks:
  web:
    external:
      name: web
